### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jkazimierczak** [dkwiecien/python_formatting_with_github_actions#2]
### Logika

- [x]  Metoda bisekcji
- [x]  Reguła falsi
- [x]  Oszacowanie dokładności wyniku
    - [x]  Osiągnięcie zadanej dokładności obliczeń *
    - [x]  wykonanie określonej przez użytkownika liczby iteracji
- [ ]  Wbudowano funkcje nieliniowe
    - [ ]  wielomian
    - [ ]  trygonometryczną (? tylko jedną ?)
    - [ ]  wykładniczą
    - [ ]  złożenia (? wszystkich powyższych ?)

### Interfejs Użytkownika

- [ ]  Użytkownik może:
    - [ ]  wybrać jedną z funkcji
    - [ ]  określić przedział, na którym poszukiwane jest miejsce zerowe
    - [ ]  wybrać kryterium zatrzymania algorytmu
        - [ ]  warunek dokładności
        - [ ]  warunek liczby iteracji
- [ ]  Program
    - [ ]  wykonuje obliczenia przy użyciu obu metod (bisekcja oraz falsi)
    - [ ]  wyświetla wyniki
    - [ ]  rysuje wykres wybranej funkcji na zadanym przedziale
        - [ ]  zaznacza rozwiązania na wykresie
    - [ ]  Sprawdza poprawność założenia o przeciwnych znakach funkcji na krańcach badanego przedziału.
    
    <aside>
    💡 Nie trzeba sprawdzać prawdziwości założeń o stałym znaku pochodnych na przedziale.
    
    </aside>
    

### Sprawozdanie

- [ ]  Oszacować dokładność obu metod
- [ ]  Porównać ich skuteczność
    - [ ]  ile iteracji potrzebna do osiągnięcia zadanej dokładności przy użyciu każdej z metod
        - [ ]  która wymaga mniej?
    - [ ]  jaką dokładność osiąga każda metoda dla określonej liczby iteracji
        - [ ]  która jest dokładniejsza?
- [ ]  Co się dzieje, jeśli założenie o stałym znaku pochodnych na przedziale nie jest spełnione?
    - [ ]  Zamieścić w sprawozdaniu przykład ilustrujący taką sytuację.
